### ISSUE TITLE
Add guidance on "flat" vs "compact".

### ISSUE THREAD

**Issue by OR13** [w3c/vc-jose-cose#107]
when credentials are present on a file system, compact is a terrible representation to use.

we should provide guidance on when to use flat and when to use compact.

**Comment by Sakurann** [comment]
sd-jwt defined how to do JSON serialization. once/if PR #149 is merged, JSON serialization section in sd-jwt should be pointed at.

**Comment by selfissued** [comment]
I agree that we should resolve this in the manner suggested by @Sakurann above.

**Comment by OR13** [comment]
lets maybe not say anything about this, and just cite sd-jwt.

**Comment by selfissued** [comment]
Let's say "Use of the JWS Compact Serialization is NOT RECOMMENDED since using multiple serializations will decrease the likelihood of interoperability between implementations."

**Comment by OR13** [comment]
I'm gonna try to address https://github.com/w3c/vc-jose-cose/issues/136 as well

**Comment by OR13** [comment]
PR is up: https://github.com/w3c/vc-jose-cose/pull/170

**Comment by OR13** [comment]
resolved by PR ^
