### ISSUE TITLE
Deprecate `vc` & `vp` ?

### ISSUE THREAD

**Issue by OR13** [w3c/vc-jose-cose#119]
These are registered claims at:

- https://www.iana.org/assignments/jwt/jwt.xhtml

As it says, the change controller is IESG, but it references v1.0 of the data model, specifically:

- https://www.w3.org/TR/2019/REC-vc-data-model-20191119/

In v2, we removed these from the core data model, and we removed them from this specification.

Should we tell the IESG to update the registry in any way?

**Comment by OR13** [comment]
https://github.com/w3c/vc-jwt/pull/124

**Comment by Sakurann** [comment]
VCDM 2.0 charter clearly states "It will replace the current [Verifiable Credentials Data Model 1.1 Recommendation](https://www.w3.org/TR/vc-data-model/)." so the best thing is probably to deprecate these claims. 

though in reality i would expect VCDM 1.1 implementations to remain in the wild so not sure what impact this deprecation will have on them. (cc: @bc-pi)

**Comment by OR13** [comment]
deprecation should not break any existing JWT implementations... JSON ignores fields it does not understand.

**Comment by Sakurann** [comment]
PR was merged
