### ISSUE TITLE
File PING request once rename is complete

### ISSUE THREAD

**Issue by mprorock** [w3c/vc-jose-cose#128]
file PING review request [here](https://github.com/w3cping/privacy-request/issues/new/choose) once renaming is complete

**Comment by OR13** [comment]
@mprorock lets kick this off.

**Comment by mprorock** [comment]
in process - expect to file monday or over the weekend

**Comment by Sakurann** [comment]
please start this..

**Comment by awoie** [comment]
> @awoie can you request the PING review? I believe that @mprorock's plate is overly full at the moment.

I can help with PING request. Although not today but can do Wednesday morning.

**Comment by awoie** [comment]
My apologies, I couldn't file the PING request this week, but will do today.

**Comment by selfissued** [comment]
Requests filed, per https://github.com/w3c/vc-jose-cose/issues/93#issuecomment-1720985793

**Comment by awoie** [comment]
I believe we can close this issue?

**Comment by OR13** [comment]
closing
