### ISSUE TITLE
signature profiles

### ISSUE THREAD

**Issue by alenhorvat** [w3c/vc-jose-cose#136]
Media type is used to express information about signature encoding.
We know that different signature profiles exist, where profiles define
- required JOSE header claims
- optional JOSE header claims
- key resolution
- etc.

DIP defines something similar: https://w3c-ccg.github.io/lds-jws2020/#json-web-signature-2020

JAdES, for example, defines a large set of registered and unregistered header params (see p43: https://www.etsi.org/deliver/etsi_ts/119100_119199/11918201/01.01.01_60/ts_11918201v010101p.pdf)

On top of this, use cases can further specify whether some optional claims are required or not.

This topic is independent of the signature serialisation (JWS compact, JWS JSON, Data Integrity Proof).

a) is there a repository for signature profiles?
b) has already been discussed how to express the signature information profile in JOSE/COSE?
c) if answers are no and no, where would be the best place to manage the information?

**Comment by OR13** [comment]
Interesting, I was just about to file a similar issue.

The current language require specific values for `typ`, for example `typ: vc+ld+json+jwt`.

I think we should update this language from MUST to SHOULD unless a "more specific media type is used in the future".... This will leave open the door for future implementations to leverage the explicit typing guidance of the JWT BCP, for specific types of JSON-LD Verifiable Credentials.

> a) is there a repository for signature profiles?

No, AFAIK there is not, but this seems like something that could be addressed in https://github.com/w3c/vc-specs-dir for profiles of W3C Verifiable Credentials.

> b) has already been discussed how to express the signature information profile in JOSE/COSE?

Yes, thats been discussed, this work item is responsible for specifying the base layer, that other profiles might build on.

> c) if answers are no and no, where would be the best place to manage the information?

This is as good a place as any for the conversation. If it looks like whats being asked for is less of a "profile" and more of "generic guidance" we might try to adjust the spec text of `vc-jose-cose`.

If the profile thread starts to get long, I might suggest addressing it in a separate document, with a registered media type in the vc-specs-dir.... Perhaps `vc+__profile__+json` or something else, etc...

**Comment by TallTed** [comment]
Media type `profiles` are parameters which follow the media type and a semicolon separator, as specified in [_§4.0 The 'Profiles' Parameter_ of RFC6381, _The 'Codecs' and 'Profiles' Parameters for "Bucket" Media Types_](https://datatracker.ietf.org/doc/html/rfc6381#section-4). The general form for `application/vc+ld+json+jwt` would be `application/vc+ld+json+jwt;profile=__profile__` or `application/vc+ld+json+jwt;profile="__profile1__,__profile2__"`. 

Several special characters, including comma separators when multiple profile values are associated with a single file, require wrapping the entire value in double-quotes (`"`).

There are also some challenging rules for encoding some characters in profile values, so my initial thought that these would be optimal as URLs may not be workable. It might be necessary to create yet another registry (or portion of registry) for these profiles.

I might suggest `application/jwt;profile="vc+ld+json"` for a document which encapsulates a `application/vc+ld+json` document.

**Comment by OR13** [comment]
You are not supposed to just take on media type parameters (even profile), they should be acknowledge when you request registration, for example:

https://www.iana.org/assignments/media-types/application/ld+json

defines profile, but:

https://www.iana.org/assignments/media-types/application/jwt

does not define profile.

I agree with your comment about not using multiple suffixes for profiles... IIRC the suffixes draft comments on how to consider media type parameters when you use multiple suffixes.

> I might suggest `application/jwt;profile="vc+ld+json"` for a document which encapsulates a `application/vc+ld+json` document.

This has been discussed several times at this point. 

It has not gotten much support because it:

1. conflates media types with profiles... although I have seen PGP examples that look like this.
2. JWT / JWS already has `cty` for this purpose... (this is the current approach the spec takes today)

**Comment by TallTed** [comment]
Yes, some media type registrations might need some updating to make profiles on them "legal".

I don't see this is any more problematic nor difficult, and really a lot easier, than registering an indeterminate number of additional media types like `vc+__profile__+sd-jwt+json` or `vc+__profile__+sd-jwt`, where each and every additional profile would require shepherding another media type registration through IANA -- unlike `;profile=__profile__` parameters which are handled (theoretically more quickly) entirely by the media type registrant in their own `profile` registry.

> [`application/jwt;profile="vc+ld+json"` for a document which encapsulates a `application/vc+ld+json` document] has not gotten much support because it:
>
> 1. conflates media types with profiles... although I have seen PGP examples that look like this.

How does this conflate media types with profiles? 

Maybe you'd prefer `application/jwt;profile="application/vc+ld+json"`, though I can hear the objections to those extra 12 characters now... which led `cty` to be `vc+ld+json` for an `application/vc+ld+json` payload... though if the payload is (for instance) an HTML document, it's gonna be `application/jwt;profile="text/html"`, not `application/jwt;profile="html"`.

> 2. JWT / JWS already has cty for this purpose... (this is the current approach the spec takes today)

Yes, `cty` exists to say that a given JWT/JWS contains an `application/vc+ld+json`, but I'm pretty sure you've been a loud voice saying that such a JWT/JWS media type should be `application/vc+ld+json+jwt` or `application/vc+ld+jwt`, not `application/jwt`, no matter what the `cty` value. Have you dropped that push?

**Comment by selfissued** [comment]
I believe that merging PR #141 and PR #149 would largely address this.

**Comment by alenhorvat** [comment]
@selfissued not entirely. I'd like to propose a separate PR that is addressing the signature profiles.

**Comment by OR13** [comment]
We could argue that signature profiles will need to be handled by other specs, similar to how SD-JWT resolved this issue

**Comment by OR13** [comment]
@alenhorvat please open a PR when you are ready, I am assigning this to you.

**Comment by OR13** [comment]
PR is up: https://github.com/w3c/vc-jose-cose/pull/170

**Comment by OR13** [comment]
resolved by PR ^
