### ISSUE TITLE
Various discussion points for VC-JWT Specification 

### ISSUE THREAD

**Issue by nadalin** [w3c/vc-jose-cose#14]
Up level the VC-JWT to be a first level data model independent from VC-Data Model specification. The current data model is not the best data model for JSON Web Tokens from many perspectives. JSON does not need C14N and JSON-LD does, there are no proven (mathematical) algorithms for C14n and JSON-LD at this point in time, We already have JWS for JWT and no need for other signature types.
 
Remove the JSON-LD requirement of having @Context as it really does not work for proper namespace declaration and interoperability

Remove the JWT claim transformation requirements (put base JWT claims in the VC Data model). There are integrity issues doing this and there is no reason to do this if we keep with the JWT signature algorithms, so should not have to transform headers or claims from JWT

The usage of JWE should not be out of scope, as this may provide selective disclosure.

There does not always have to be  a relationship between the verifier and issuer, if the verifier has to trust the issuer then there is a relationship, this can and will lead to collusion. The verifier only has to verify the signature of the verifier not trust.

There are concerns about the proof_property and if this is a MUST or a MAY, as the spec seems to contradict itself
Could be editorial bugs. We tried to differentiate between credentials (no proof) and verifiable credentials (with proof). There are probably editorial errors which you could point out and get fixed

**Comment by TallTed** [comment]
@nadalin -- Please edit [your initial comment here](https://github.com/w3c/vc-jwt/issues/14#issue-1373765719), and wrap the `@context` string (in your second paragraph) in a code fence (easiest is single backticks, as ``` `@context` ```), as that GitHub user has never participated in any relevant discussions or groups.

**Comment by mprorock** [comment]
> > Remove the JSON-LD requirement of having `@context` as it really does not work for proper namespace declaration and interoperability
> 
> -1 to this.

big -1 to this as well - I concur with Orie on this and feel that removal of `@context` is extremely harmful to the work in general and will lead to fragmentation, much less remove much of the meaning and power that VCs have.  I am however, a fan of, and understand the need for private claims - adding a sane `@vocab` entry to the main context would facilitate this quite nicely

+1 to this:

> We now have iss and issuer. In order to preserve semantic processing after verification (see first comment). We need to include @context in the claims set, and it needs to provide term mapping for iss to issuer (the IRI part, not the term part). And same for all the other "in addition to" claims.
> 
> This then allows for VC-JWT to be processed identically to any other well formed graph fragment.
> 
> I could get behind such a simplification to the mapping rules, if the complexity moved from the mapping to the context, so that semantics were preserved 1-1.

**Comment by OR13** [comment]
This issue seems to be stale

**Comment by OR13** [comment]
Marked pending close over 1 week ago, closing.
