### ISSUE TITLE
Define Controller Documents in the Core Data Model

### ISSUE THREAD

**Issue by OR13** [w3c/vc-jose-cose#140]
Originally https://github.com/w3c/vc-data-integrity/pull/99#pullrequestreview-1501967239

As discussed on the call today, we want to remove bias towards specific key and securing formats in the core data model.

We want to improve on what DID Core has done.

**Comment by selfissued** [comment]
PR #144 should address this.

**Comment by OR13** [comment]
Seems still blocked pending: https://github.com/w3c/did-core/issues/845

**Comment by OR13** [comment]
Given the resolutions this is now post CR.

**Comment by decentralgabe** [comment]
VC JOSE COSE should be updated to define the profile of the Controller Document spec we are using.

@selfissued to take note after the Controller Document spec is in a good state.
