### ISSUE TITLE
Describe why core data model members are translated to JWT claims

### ISSUE THREAD

**Issue by OR13** [w3c/vc-jose-cose#15]
> Can we add an explanation why do these members need to be translated to the equivalents of the JWT claims?
iss, nbf, all of them are optional in RFC 7519 itself. They only become required when the JWT is used for a specific purpose, and the only place I can think of right now is an ID Token.

See: https://github.com/w3c/vc-jwt/pull/11#discussion_r959861979

**Comment by TallTed** [comment]
Should the title of this issue be `Describe why core...` instead of `Describe my core...`?

**Comment by selfissued** [comment]
The "iss", "iat", and "exp" claims are required in most secure profiles of JWTs.  We should do the same.

Likewise, "kid" is typically a required header parameter (as of course, is "alg").

**Comment by OR13** [comment]
I am a +1 to making `iat` explicitly required... 

I am a -1 to making `exp` required (core data model does not require it so this isn't the right place to argue that anyway).

`iss` is already required by the core data model.

**Comment by OR13** [comment]
This can be closed when #88 is merged

**Comment by OR13** [comment]
@selfissued blocked by the same PR

**Comment by TallTed** [comment]
> [@OR13] blocked by the same PR

Does this refer to #88? 

Please refer to PRs and Issues by link/number, rather than indefinite things like "same PR".

**Comment by Sakurann** [comment]
#88 was merged
