### ISSUE TITLE
credentialSchema property not fully correct in PR#159 examples

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-jose-cose#164]
Whilst the first tab of Example 1 (application/vc+ld+json) is correct, I do not believe that the third tab (application/vc+ld+json+sd-jw) is correct as it places the credentialSchema as a property of the credentialSubject

**Comment by decentralgabe** [comment]
I can't seem to find this. Maybe it has been fixed? Please let me know if you still see it.

**Comment by David-Chadwick** [comment]
This is because the second and third tabs have been removed from the example. I do not know which PR did this, but I would have thought that the correct approach was to fix the tabs rather than to remove them. Personally I found the tabs to be useful as they showed how the VC evolved to be a JWT

**Comment by decentralgabe** [comment]
@OR13 thoughts?

**Comment by TallTed** [comment]
> [@David-Chadwick] the second and third tabs have been removed from the example

The tabs (both labels and content) of this example have been changed substantially, but I don't think anything has been removed. See the [latest Editor's Draft](https://w3c.github.io/vc-jose-cose/#example-a-simple-example-of-a-verifiable-credential).

[Look particularly](https://w3c.github.io/vc-jose-cose/#example-a-simple-example-of-a-verifiable-credential) to where `credentialSchema` appears in what is now the fifth tab, now titled "Verified", which is part of what replaced [what was in the third tab](https://pr-preview.s3.amazonaws.com/David-Chadwick/vc-jose-cose/pull/159.html#example-example-credential), then titled `application/vc+ld+json+sd-jwt`.

I believe that the concern about `credentialSchema` that @David-Chadwick raised in [the initial comment here](https://github.com/w3c/vc-jose-cose/issues/164#issue-1939710956) has been resolved.

**Comment by David-Chadwick** [comment]
The tabs have come back and now the content is correct, so this issue can be closed. 

I suspect that @decentralgabe and myself viewed a temporary draft that was in the process of being fixed as a result of this issue (the first step being to remove wrong content, and the second step being to add the corrected content).
