### ISSUE TITLE
Example does not correspond to description in section 5.3.1

### ISSUE THREAD

**Issue by bert-github** [w3c/vc-jose-cose#167]
The description of [Example 12](https://www.w3.org/TR/2023/WD-vc-jose-cose-20231016/#example-various-verification-method-types) says:

> […] For example, expressing key material in a [verification method](https://www.w3.org/TR/2023/WD-vc-jose-cose-20231016/#dfn-verification-method) using both publicKeyJwk and publicKeyMultibase at the same time is prohibited.
> 
> An example of a [controller document](https://www.w3.org/TR/2023/WD-vc-jose-cose-20231016/#dfn-controller-documents) containing [verification methods](https://www.w3.org/TR/2023/WD-vc-jose-cose-20231016/#dfn-verification-method) using both properties above is shown below.

However, the example does _not_ contain both properties. It only contains ‘publicKeyJwk’.

**Comment by decentralgabe** [comment]
fixed in #176
