### ISSUE TITLE
Missing word and missing referent in section 2

### ISSUE THREAD

**Issue by bert-github** [w3c/vc-jose-cose#169]
In [section 2](https://www.w3.org/TR/2023/WD-vc-jose-cose-20231016/#terminology), the definition of a decentralized identifier (DID) contains the phrase ‘The generic format of a is defined in […]’. This probably lacks the word ‘DID’ after ‘a’.

Also, the next sentence mentions a ‘method’, but it is not clear what the method is for: generating? registering? identifying? Maybe this should say ‘method to register DIDs’.

**Comment by decentralgabe** [comment]
fixed in #176
