### ISSUE TITLE
Remove internationalization considerations section?

### ISSUE THREAD

**Issue by aphillips** [w3c/vc-jose-cose#172]
9.4 Internationalization
https://www.w3.org/TR/2023/WD-vc-jose-cose-20231016/#internationalization

> This section is non-normative.
>
> Implementers should take into account several internationalization considerations when publishing data described in this specification. Disregarding internationalization hampers the production and consumption of data across diverse languages and societies, thereby restricting the applicability and significantly reducing the value of the specification as a standard.
>
> Implementers are advised to note and abide by all internationalization considerations called out in the [[VC-DATA-MODEL](https://www.w3.org/TR/2023/WD-vc-jose-cose-20231016/#bib-vc-data-model)], see also [i18n](https://www.w3.org/standards/webdesign/i18n), [URL Standard](https://url.spec.whatwg.org/)

The section contains nothing concrete, except a link to the [Verifiable Credentials Data Model 1.1](https://www.w3.org/TR/vc-data-model/) spec. That spec in turn refers to [string-meta](https://www.w3.org/TR/string-meta/) and gives examples of dealing with localizable text.

However, there doesn't seem to be any localizable text in vc-jose-cose itself. So this reference serves no purpose.

Consider removing this section.

(Filing on behalf of the reviewer @bert-github)

**Comment by selfissued** [comment]
I agree with the removal.
