### ISSUE TITLE
Add a reference to Data Integrity Specification Registries when it exists

### ISSUE THREAD

**Issue by decentralgabe** [w3c/vc-jose-cose#173]

**Comment by decentralgabe** [comment]
cc: @msporny does it / will it exist?

**Comment by msporny** [comment]
At present, it looks like the VC Specifications Directory is going to be where this information is placed (that's where the cryptosuites are listed now, under the Proof section): https://w3c.github.io/vc-specs-dir/#proof

**Comment by decentralgabe** [comment]
thanks, will update the link in this spec to point to that.
