### ISSUE TITLE
Add comments on encryption re:OpenID

### ISSUE THREAD

**Issue by decentralgabe** [w3c/vc-jose-cose#175]
>  The working group is discussing how we might comment on recent work, that does make use of encryption in https://openid.net/specs/openid-4-verifiable-presentations-1_0.html#section-3.2

**Comment by selfissued** [comment]
We could say that JOSE and COSE objects can be encrypted after being signed.  That said, how to obtain the encryption keys is beyond the scope of the specification.

**Comment by decentralgabe** [comment]
@selfissued to add comments on how JOSE and COSE support encryption 

Updated spec link: https://openid.net/specs/openid-4-verifiable-presentations-1_0.html#name-signed-and-encrypted-respon
