### ISSUE TITLE
Adjust Explicit Typing Guidance regarding `typ`

### ISSUE THREAD

**Issue by OR13** [w3c/vc-jose-cose#184]
Per the comment here: https://github.com/w3c/vc-jose-cose/pull/183/files#r1405326097

This would still have the core data model taking a dependency on multiple suffixes, but it would make it so that there was no specific typ for W3C JSON-LD SD JWT VCs, which would counter the guidance from the IETF OAuth WG and the JWT BCP.

If we can't get consensus on the use of `typ` at W3C, we can remove references to it, such that profiles can lock down the behavior / comply with the JWT BCP... I am leaning towards that approach.

**Comment by OR13** [comment]
> As noted many other places, just as there is no such thing as `application/jpg+zip`, the `application/vp+ld+json+sd-jwt` media type should not exist; this media type should be simply application/sd-jwt. The described reasoning behind wanting media types like `application/vp+ld+json+sd-jwt` would be well satisfied and better conform to RFC history by specifying profiles for the `application/sd-jwt`media type.

- https://github.com/w3c/vc-jose-cose/pull/183#pullrequestreview-1749264253

**Comment by OR13** [comment]
I sent a message to both the OAuth and Media Types lists at IETF:

- https://mailarchive.ietf.org/arch/msg/oauth/utKyjvovcqguwkAUTYVW-C6Yw-w/
- https://mailarchive.ietf.org/arch/msg/oauth/BkMuRmt6zExtr1TdsxX37pZtyfY/

**Comment by OR13** [comment]
Related: https://github.com/w3c/vc-jose-cose/issues/179

**Comment by OR13** [comment]
PR is up here: https://github.com/w3c/vc-jose-cose/pull/186

**Comment by selfissued** [comment]
Categorizing as post-CR, per decision on 20-Dec-23 working group call.

**Comment by TallTed** [comment]
Please use ISO 8601 date format, or at least 4-digit years. Ambiguous date formats cause [endless trouble](https://xkcd.com/1179/).

`20-Dec-23` ==> `2023-12-20` or `20-Dec-2023`

**Comment by selfissued** [comment]
We are using "typ" in the spec at this point.  Therefore, I believe this can be closed, unless I'm missing something.
