### ISSUE TITLE
Write an algorithm for verifying VC/VP JWTs

### ISSUE THREAD

**Issue by jyasskin** [w3c/vc-jose-cose#187]
@OR13 [mentioned](https://github.com/w3c/vc-data-model/pull/1338#discussion_r1407889636) that the bulk of this algorithm is a call to either https://www.rfc-editor.org/rfc/rfc7515.html#section-5.2 or https://www.rfc-editor.org/rfc/rfc7519.html#section-7.2 (which one?), but the algorithm should include at least
- [ ] any "application decision"s that those specs ask for
- [ ] the restrictions from https://w3c.github.io/vc-jose-cose/#key-discovery
- [ ] a description of when any remote resources are dereferenced/fetched, for example to find controller documents and keys.

**Comment by selfissued** [comment]
Addressed by https://github.com/w3c/vc-jose-cose/pull/190
