### ISSUE TITLE
Do we need an SD-JWT profile for W3C VCs?

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-jose-cose#191]
Apologies if this topic has already been discussed in the VC WG and I missed it.

The current work on SD-JWT is being carried out in the IETF. A profile of SD-JWT is also being created for "verifiable credentials" but this draft contains the following note "This specification does not utilize the W3C's Verifiable Credentials Data Model v1.0, v1.1, or v2.0."

This poses the following questions.
Q1. Does this working group think that there should be a specification of how to use SD-JWT to create W3C VCDM conformant VCs?
If the answer to Q1 is yes, then
Q2. Is it within the scope of the current WG to create a profile of SD-JWT that does utilise the W3C VCDM?
Q3. If not, does W3C have any other mechanism for creating such a profile?

**Comment by David-Chadwick** [comment]
This issue should remain open until the following issues are fixed
1. This spec is now based on SD-JWT, whereas the first draft was not. Consequently the title of the spec should be changed to indicate that selective disclosure is supported. (Otherwise how will people intuitively know that it is for SW-JWT and not plain JWT). I suggest something like "Securing Verifiable Credentials and supporting selective disclosure using JOSE and COSE"
2. [SD-JWT-VC] is in the list of references but is not referenced in the body of the document.
3. The examples are not as clear as those in the SD-JWT specification. For example, no disclosures are shown unencoded

**Comment by selfissued** [comment]
Thanks for your comments, @David-Chadwick .  Here are my thoughts:
1. I am against making the title longer.  Just like VCDM supports selective disclosure but doesn't say so in the title, it's fine to likewise not say so in the title.
2. Where in the body of the spec do you suggest referencing [SD-JWT-VC]?
3. Where would you like to see an enhanced example?

**Comment by David-Chadwick** [comment]
1. But the SD-JWT-VC IETF draft does specify selective disclosure in its title, even though it does not support W3C VCs. So by looking at the titles of both specs, readers will falsely think that the IETF draft is the only spec that supports W3C VCs and selective disclosure, and that our spec does not support it. This is obviously wrong, so we should try to help new readers who are presented with a list of titles to choose the correct standard.
2. Sorry for the confusion, I am suggesting that the reference should be removed, not that we add text to reference it.
3. Example 1 would be a good start. Perhaps a tab can be added to show the disclosures, or text could be added below the example to enumerate the disclosures.

**Comment by selfissued** [comment]
Per 2, [SD-JWT-VC] was actually referenced several places, but using the wrong Markdown syntax.  https://github.com/w3c/vc-jose-cose/pull/198 fixes this.

Per discussion on the 20-Dec-23 working group call, I don't think there's consensus to do 1.

We can take up 3 after CR, but given it doesn't change the meaning of the spec, it's not critical to go to CR.

**Comment by David-Chadwick** [comment]
Please re-open this issue as it has not been completed yet. It can be marked post-CR if you like, but until point 3 has a PR prepared for it,  then this issue should not be closed.

**Comment by decentralgabe** [comment]
@David-Chadwick I opened a separate issue to track this https://github.com/w3c/vc-jose-cose/issues/199

**Comment by David-Chadwick** [comment]
I have raised PR#212 to address the title issue. This does not make the title any longer, and furthermore it accurately reflects what the spec is about. Furthermore it is consistent with the Introduction section of the specification, which the original title no longer is
