### ISSUE TITLE
Text about obtaining the right verification key

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-jose-cose#194]
The proposed verification algorithm text will say " This specification might be used with many different key discovery protocols. As such, discovery of verification keys is described in a different section of this document, and is assumed to have succeeded prior to beginning the verification process. "

First there should be a reference to the "different section of this document".

Second, this different section needs to have text about obtaining the right/current key and not an old e.g. revoked key. This section should also contain text about using/not using the credentialStatus property since this is critical to ensuring you have the right key.

**Comment by selfissued** [comment]
@David-Chadwick, is there corresponding text about obtaining a valid key in the Data Integrity spec that you'd like us to mirror here?  Whatever we say in this regard should be actionable and not vague, should we say anything at all.

With respect to `credentialStatus`, we already say "Status extension mechanisms such as credentialStatus SHOULD be checked. If the extension mechanism type is not understood, this property MUST be ignored."

**Comment by David-Chadwick** [comment]
"`Status extension mechanisms such as credentialStatus SHOULD be checked. If the extension mechanism type is not understood, this property MUST be ignored`."

This is the opposite of good security practice. If a relying party cannot interpret status information it MUST assume that the credential has been revoked.

**Comment by selfissued** [comment]
Actually, thinking about it, describing how to use `credentialStatus` is the job of VCDM - not securing specifications.  Talking about it here is a layering violation.  Unless there's a reason that I'm wrong about that, I plan to remove the offending sentence from this securing specification.

**Comment by David-Chadwick** [comment]
It depends. If a specific VC has been revoked, then it is the job of the validation function to determine if the VC is still valid, as you say. But if the issuer's key has been compromised, meaning that a whole bunch of VCs have to be revoked, then its a function of the key management system to check that the issuer's key has not been revoked. This is part of the verification function. Remember that the VC that is being verified could be many months old, during which time the issuer could have had a mishap with its signing key. So the VC that is being verified might be a fake one, created with the compromised key, and backdated to several months ago. So the securing mechanism needs a way to check that the signing key is still good.
