### ISSUE TITLE
https://w3c.github.io/vc-jose-cose/ is not being updated

### ISSUE THREAD

**Issue by selfissued** [w3c/vc-jose-cose#196]
https://w3c.github.io/vc-jose-cose/ is stuck in July 2023 whereas https://www.w3.org/TR/vc-jose-cose/ is being updated.  Yet, the former is the one referenced from https://github.com/w3c/vc-jose-cose/.

Can we please fix the build process to update the editor's draft at https://w3c.github.io/vc-jose-cose/?

Thanks.

**Comment by iherman** [comment]
This issue should be closed if PR #197 solves the issue.

**Comment by selfissued** [comment]
Fixed by https://github.com/w3c/vc-jose-cose/pull/197
