### ISSUE TITLE
Add an example for selective disclosure

### ISSUE THREAD

**Issue by decentralgabe** [w3c/vc-jose-cose#199]
> 1. But the SD-JWT-VC IETF draft does specify selective disclosure in its title, even though it does not support W3C VCs. So by looking at the titles of both specs, readers will falsely think that the IETF draft is the only spec that supports W3C VCs and selective disclosure, and that our spec does not support it. This is obviously wrong, so we should try to help new readers who are presented with a list of titles to choose the correct standard.
> 2. Sorry for the confusion, I am suggesting that the reference should be removed, not that we add text to reference it.

Handled in #198 #191

> 3. Example 1 would be a good start. Perhaps a tab can be added to show the disclosures, or text could be added below the example to enumerate the disclosures.

To be handled

_Originally posted by @David-Chadwick in https://github.com/w3c/vc-jose-cose/issues/191#issuecomment-1865028086_

**Comment by TallTed** [comment]
Please edit initial comment and delete leading spaces, such that list item 1 is not presented as code.

**Comment by David-Chadwick** [comment]
PR #215 addresses this issue for example 1.
Another similar PR is also needed for example 2.

**Comment by decentralgabe** [comment]
This is completed

**Comment by David-Chadwick** [comment]
Half completed!!

**Comment by decentralgabe** [comment]
@David-Chadwick are you suggesting an example for SD-JWT-VC?

**Comment by David-Chadwick** [comment]
No, for the VP in example 2

**Comment by decentralgabe** [comment]
This was fixed by #241
