### ISSUE TITLE
Data format for COSE_Key expression in Controller Document is undefined

### ISSUE THREAD

**Issue by msporny** [w3c/vc-jose-cose#208]
In Section 5.3.1.1 Verification Material, it states that a `COSE_Key` property is allowed, but then doesn't specify the data format. Should this include something like `CoseWebKey` or `publicKeyCwk`? Or is something else expected to be defined here?

**Comment by selfissued** [comment]
There's no need to add COSE_Key representations to controller documents.  JWK is equivalent and can be used instead.  JWK, like controller documents, are JSON, whereas adding binary COSE_Key values to JSON would be awkward, at best.

**Comment by msporny** [comment]
> There's no need to add COSE_Key representations to controller documents.

Then the specification shouldn't say that a "COSE_Key" property is allowed. Remove the text that suggests that there is a "COSE_Key" format.
