### ISSUE TITLE
Inconsistent sectioning?

### ISSUE THREAD

**Issue by iherman** [w3c/vc-jose-cose#216]
The current sectioning is as follows:

- §3 Securing the VC Data Model
    - § 3.1 With JOSE
    - § 3.2 With COSE
    - $ 3.3 JOSE Header Parameter and JWT claims
- § 4. COSE Header Parameters and CWT claims  

Shoudn't be either

- § 4 should be in fact § 3.4; or
- § 3.3. should be §4 (and the rest of the main sections shift accordingly; or
- there should be a separate § 4 with a title along the lines of "Header Parameters" with a subsection for JOSE and COSE respectively ;
- like before, but as a subsection to § 3

I am not a domain expert, so I cannot choose which solution is the best.

**Comment by brentzundel** [comment]
@decentralgabe @selfissued 
I propose the following options for restructuring:

- §3 Securing the VC Data Model
  - § 3.1 With JOSE
  - § 3.2 With COSE
- §4 Header Parameters
  - §4.1 JOSE Header Parameter and JWT claims
  - §4.2 COSE Header Parameters and CWT claims

or 

- §3 Securing the VC Data Model
  - § 3.1 With JOSE
     - §3.1.1 JOSE Header Parameter and JWT claims
  - § 3.2 With COSE
     - §3.2.1 COSE Header Parameters and CWT claims

Let me know your preference and I will raise a PR.

**Comment by TallTed** [comment]
@brentzundel — I think the latter suggestion is better.

**Comment by decentralgabe** [comment]
agree on the latter

**Comment by selfissued** [comment]
The latter also works for me.

**Comment by brentzundel** [comment]
I will raise a PR to make the changes, but plan to wait until #231 is merged as I expect conflicts if both are pursued simultaneously.

**Comment by iherman** [comment]
Looking at the latest version of the spec (08 March 2024), this Issue has been completed and is not relevant any more. Closing.
