### ISSUE TITLE
Example 24 is invalid

### ISSUE THREAD

**Issue by iherman** [w3c/vc-jose-cose#217]
[Example 24](https://www.w3.org/TR/vc-jose-cose/#example-presentation) uses the `verifiableCredential` property to refer to several credentials. However, the [formal definition of this property](https://www.w3.org/TR/vc-jose-cose/#example-presentation) says:

> The value MUST be one or more [verifiable credential](https://www.w3.org/TR/vc-data-model-2.0/#dfn-verifiable-credential) and/or [enveloped verifiable credential](https://www.w3.org/TR/vc-data-model-2.0/#enveloped-verifiable-credentials) objects (to be clear, the values MUST NOT be non-object values such as numbers, strings, ***or URLs***).

(Emphasis is mine.). In other words, these lines of the example:

```json
    "https://vendor.example/credentials/42", 
    "did:example:123",
    "urn:uuid:01ec9426-c175-4e39-a006-d30050e28214",
    "urn:ietf:params:oauth:jwk-thumbprint:sha-256:_Fpfe27AuGmEljZE9s2lw2UH-qrZLRFNrWbJrWIe4SI",
    "data:application/vc+ld+json+sd-jwt;…"
```

are all forbidden per the VCDM spec and must be removed. (Or exchanged for a bona fide JSON object for another credential.)

**Comment by decentralgabe** [comment]
Believe this should be updated to use the enveloped property.

**Comment by iherman** [comment]
@decentralgabe:
> Believe this should be updated to use the enveloped property.

Yes, but only partially. The [definition of the Enveloped Verifiable Credential](https://www.w3.org/TR/vc-data-model-2.0/#enveloped-verifiable-credentials) class (not property) stipulates the usage of a data URI. I.e., the last entry in the example can indeed be changed to:

```json
{
    "@context": "https://www.w3.org/ns/credentials/v2",
    "id" : "data:application/vc+ld+json+sd-jwt;…",
    "type": "EnvelopedVerifiableCredential"
}
```

But I am afraid there is no standard way to express the preceding URLs in the example.

**Comment by decentralgabe** [comment]
fixed by https://github.com/w3c/vc-jose-cose/pull/241
