### ISSUE TITLE
Clarify relationship between "iss" and "issuer"

### ISSUE THREAD

**Issue by selfissued** [w3c/vc-jose-cose#22]
The VC Data Model spec says this about the `issuer`:
> The value of the issuer [property](https://www.w3.org/TR/vc-data-model/#dfn-property) MUST be either a [URI](https://www.w3.org/TR/vc-data-model/#dfn-uri) or an object containing an id [property](https://www.w3.org/TR/vc-data-model/#dfn-property).

The VC-JWT spec says this about the `issuer`:
> iss MUST represent the issuer property of a verifiable credential or the holder property of a verifiable presentation.

The JWT spec says this about `iss`:
> The "iss" value is a case-sensitive string

That means that that if `issuer` is an object containing an id [property](https://www.w3.org/TR/vc-data-model/#dfn-property), it is incompatible with `iss`, since `iss` is a string.  We clearly need language describing this type mismatch and how to avoid it and/or what the `iss` value must be when `issuer` is an object that is not a string.

Attn: @OR13

**Comment by OR13** [comment]
I don't agree, I think `issuer` as an object is legal according to the core data model, and compatible with `iss` WHEN, a clean mapping in normative text exists of the following format:

If `issuer` is a string, `iss` MUST match `issuer`.

If `issuer` is an object with an `id` value, `iss` MUST match the `id` value.

This is how we support JWT / Data Integrity Proof graph based interoperability today.

The solution is to refine the production / consumption rules to make these transformations unambiguous.

**Comment by selfissued** [comment]
Can you write a PR to do this, @OR13 ?
> The solution is to refine the production / consumption rules to make these transformations unambiguous.

Do you agree with this proposed resolution, @Sakurann ?

**Comment by TallTed** [comment]
Does `iss` map to `issuer` or `issuanceDate`? See https://github.com/w3c/vc-jwt/pull/11/files#r1000766891

**Comment by Sakurann** [comment]
> Does iss map to issuer or issuanceDate? 

In v1.1 it's issuer.

**Comment by alenhorvat** [comment]
If issuer is a string, iss MUST match issuer.
If issuer is an object with an id value, iss MUST match the id value.

Fully support this.

**Comment by OR13** [comment]
https://github.com/w3c/vc-jwt/pull/111#discussion_r1248305352

^ related

**Comment by Sakurann** [comment]
PR merged
