### ISSUE TITLE
Register COSE Media Type Suffixes

### ISSUE THREAD

**Issue by decentralgabe** [w3c/vc-jose-cose#224]
note from @msporny to possibly include suffixes on `+json+cose` `+ld+json+cose`

_Originally posted by @decentralgabe in https://github.com/w3c/vc-jose-cose/issues/223#issuecomment-1908477119_

**Comment by decentralgabe** [comment]
@selfissued what do you think?

**Comment by selfissued** [comment]
Depending upon what happens in the MediaMan WG in the IETF, @msporny is probably right about the need for these registrations.
