### ISSUE TITLE
Clarity around any terms that must be disclosed (section 3.1.1)

### ISSUE THREAD

**Issue by paulfdietrich** [w3c/vc-jose-cose#234]
This section details how to use JOSE to secure verifiable credentials conforming to

I think the details are incomplete.  I'd like to see some language here with the standard weighing in on what fields of the commited document can be selectively disclosed (marked !sd in this notation).

Can I and should I selectively disclose the following fields or must I not selectively disclose them 
 @context
issuer
credential subject

It seems like a good case could be made to have these terms always present.

**Comment by decentralgabe** [comment]
This should be handled by https://github.com/w3c/vc-jose-cose/issues/201, leaving open until a review is up for that to make sure.

**Comment by selfissued** [comment]
Addressed by #201
