### ISSUE TITLE
followup to #226, further clarifying semantics between jwt claims and vc properties

### ISSUE THREAD

**Issue by TallTed** [w3c/vc-jose-cose#235]
_Originally posted by @TallTed in https://github.com/w3c/vc-jose-cose/pull/226#discussion_r1490127211_

_Edited somewhat for posting as a new issue._

Answering @David-Chadwick's https://github.com/w3c/vc-jose-cose/pull/226#issuecomment-1944514573 --

> @decentralgabe This PR was merged without addressing my requested editorial change.

I *think* you're referring to [this comment](https://github.com/w3c/vc-jose-cose/pull/226#discussion_r1483325600) as your "requested editorial change".

Please note that your intent was not obvious because you did not submit it as a change request using the GitHub tooling, which would have shown the existing PR content --

```
        Implementers SHOULD avoid setting JWT claims to values that conflict with
        verifiable credential properties, especially with pairs such as
        `iss` and `issuer`, `jti` and `id`, and `sub` and `credentialSubject.id`.
```

-- in contrast to your suggestion --

```
        Implementers SHOULD avoid setting JWT claims to values that conflict with
        verifiable credential properties when the claims and properties refer to the same concept, for example,
        `iss` and `issuer`, `jti` and `id`, and `sub` and `credentialSubject.id`.
```

I suggest the following --

```suggestion
        Implementers SHOULD avoid setting JWT claims to values that conflict with
        the values of verifiable credential properties when a claim and property 
        pair refer to the same conceptual entity, especially with pairs such as
        `iss` and `issuer`, `jti` and `id`, and `sub` and `credentialSubject.id`.
        For example, JWK claim `iss` should not be set to a value which conflicts
        with the value of verifiable credential property `issuer`.
```

I think this change should only touch this paragraph, is editorial, and hopefully is not controversial.

**Comment by David-Chadwick** [comment]
@TallTed I like your improved text, thanks
