### ISSUE TITLE
Update example rendering for JOSE / COSE

### ISSUE THREAD

**Issue by decentralgabe** [w3c/vc-jose-cose#240]
I suggest that the Disclosed tab should be renamed to Credential and be the first tab in the set, since this appears to be the raw credential before it undergoes any processing

_Originally posted by @David-Chadwick in https://github.com/w3c/vc-jose-cose/pull/237#pullrequestreview-1888208624_
            

Also the `verified` tab should correctly display enveloped credentials as per @iherman's comment here https://github.com/w3c/vc-jose-cose/pull/239#issuecomment-1953970067

**Comment by decentralgabe** [comment]
@David-Chadwick this should be fixed by uptaking @OR13's change set here https://github.com/transmute-industries/respec-vc-jwt/pull/5 which supports examples for more than SD-JWT.

I will make sure this gets done.

**Comment by decentralgabe** [comment]
flagging there are some comments from @TallTed [here](https://github.com/w3c/vc-jose-cose/pull/237) that I will include in this change set.

**Comment by David-Chadwick** [comment]
Thanks. Looking forward to reviewing the PR
