### ISSUE TITLE
Section references not rendering

### ISSUE THREAD

**Issue by selfissued** [w3c/vc-jose-cose#262]
The section references at https://w3c.github.io/vc-jose-cose/#conformance-classes do not include section names.  For instance, the source `Section <a href="secure-with-jose"></a>.`  renders as "Section .".

The href syntax appears to be correct, since the equivalent syntax in VCDM `Section <a href="#privacy-considerations"></a>.` renders as "Section [8. Privacy Considerations](https://w3c.github.io/vc-data-model/#privacy-considerations).".

I'm guessing that we have to reference fragments corresponding to the section titles, rather than `id` values.  I'll create a PR to test that assumption.

**Comment by TallTed** [comment]
Preserving the solution here, as issue content tends to be more visible than PR comments.

@iherman said:
> The correct syntax is, e.g. `<a href="#secure-with-hose">`. Without the `#` the reference is to an outside resource identified by a relative URI. With `#` it is a fragment reference.
>
> The only magic respec does is, when a fragment URI is used, is to extract the section title and put it into the text.
