### ISSUE TITLE
Show headers in examples

### ISSUE THREAD

**Issue by martinthomson** [w3c/vc-jose-cose#271]
The examples show compact JWT and CWT text and payloads, but none show the header.  The header is the most interesting part in some ways.

**Comment by decentralgabe** [comment]
@martinthomson I believe the CWT headers are present in the diagnostic notation? https://w3c.github.io/vc-jose-cose/#securing-json-ld-verifiable-credentials-with-cose

for JWT/SD-JWT I agree it would be nice to show the headers, I can make that update.
