### ISSUE TITLE
Determine whether to include content from Verifiable Credentials Implementation Guidelines

### ISSUE THREAD

**Issue by selfissued** [w3c/vc-jose-cose#28]
A note says:
> For more information about using JOSE header parameters and/or JWT claim names not specified herein, see the Verifiable Credentials Implementation Guidelines [[VC-IMP-GUIDE](https://w3c.github.io/vc-jwt/#bib-vc-imp-guide)] document.

We should review what the guidelines say about JWTs and if some of the information would be directly useful to implementers, consider pulling it into the VC-JWT spec itself.

**Comment by OR13** [comment]
Is this still valid?

**Comment by OR13** [comment]
Removing pending close, I object to pulling in content from imp guide... Which needs to be updated very badly... cc @mprorock @selfissued

**Comment by Sakurann** [comment]
a note pointing to vc-imp-guide has been removed in the latest version of vc-jose-cose
