### ISSUE TITLE
Examples are not populated

### ISSUE THREAD

**Issue by scouten-adobe** [w3c/vc-jose-cose#286]
The example tabs, other than first tab, are blank.

As an example, view [Example 5: A simple example of a verifiable credential secured with COSE](https://www.w3.org/TR/vc-jose-cose/#example-a-simple-example-of-a-verifiable-credential-secured-with-cose).

The "Credential" tab is fine and populated as expected.

The "cose" tab has no content.

**Comment by scouten-adobe** [comment]
A CBOR-DIAG showing the fully-formed data structure would be very helpful.

**Comment by decentralgabe** [comment]
this looks to be an issue with the W3C processing somewhere...as the examples load on this link: https://w3c.github.io/vc-jose-cose/#securing-vps-with-cose

@iherman do you have an idea of where I could find logs of where things are going awry?

**Comment by scouten-adobe** [comment]
@decentralgabe that link is very helpful. Thank you!

**Comment by decentralgabe** [comment]
Seems related to https://github.com/w3c/respec-vc/issues/34

**Comment by BigBlueHat** [comment]
This should be fixed in https://github.com/w3c/respec-vc/releases/tag/3.3.5
