### ISSUE TITLE
No normative statement wrt. JWT encoding of `verifiableCredential` as base64url

### ISSUE THREAD

**Issue by msporny** [w3c/vc-jose-cose#3]
Example 31 in the specification currently presumes base64url-encoding when embedding VCs in JWT-encoded VPs:

https://w3c.github.io/vc-data-model/#example-31-jwt-payload-of-a-jwt-based-verifiable-presentation-non-normative

There is no normative specification language related to this particular transformation to/from base64url.

**Comment by selfissued** [comment]
I agree with @David-Chadwick that it's sufficient for JWTs to be encoded as defined by RFC 7519.  The base64url encodings are defined there (actually, transitively by RFC 7515 (JWS) and RFC 7516 (JWE)).

**Comment by Sakurann** [comment]
actually, I question if a base64url encoded JWT-VC has to be included inside a JWT-VP as a claim.
from a cryptography/security perspective, if VP is signed using a holder's key that is included in an issuer-signed VC, VC and VP can be sent as separate strings. including vc inside a vp almost gives a false sense of security.

**Comment by David-Chadwick** [comment]
There are two separate issues here
1. How is the credential inserted as `vc` claim in a JWT proofed verifiable credential
2. How is a verifiable credential inserted into a `vp` claim of a JWT proofed verifiable presentation.
My answers to the above are: 
1. the `vc` claim should be the unaltered JSON of the credential
2. the `vp` claim should be the unaltered JSON of the presentation. The verifiableCredential property of the presentation must be a verifiable credential in any allowed format. So it does not have to be a JWT VC, it can be a JSON-LD proofed VC.

**Comment by OR13** [comment]
This seems outdated, I suggest closing since we don't refer to v1.1 anymore.

**Comment by OR13** [comment]
Marked pending close over 1 week ago, closing.
