### ISSUE TITLE
Almost no sections are `class="normative"`. Why?

### ISSUE THREAD

**Issue by TallTed** [w3c/vc-jose-cose#300]
https://github.com/w3c/vc-jose-cose/blob/befdeae56c01fb9f790bca348ddb57f9ab5f59f3/index.html#L394

This section is one of *very* few marked explicitly as `normative`, though the introduction says that anything not marked `non-normative` *is* normative.

Why is *this* section explicitly marked `normative`? Why are the others _not_?

**Comment by decentralgabe** [comment]
Mostly an oversight, and we don't gain much benefit aside from some lint warnings, I believe. Regardless, happy to add these in.

**Comment by selfissued** [comment]
Given that stuff is already explicitly normative unless stated otherwise, I would remove the uses of  `class="normative"`.

**Comment by TallTed** [comment]
Since `class="normative"` doesn't result in anything in the post-ReSpec document, I think it would be OK to remove the few existing instances of it in the source.

At the same time, clarity for source contributors — past, present, and future — might be improved by explicitly tagging _all_ sections (and subsections) as `class="normative"` or `class="informative"`, as appropriate.
