### ISSUE TITLE
`vc-jose-cose` cannot restrict use of specific JWT Claim Names "in any JWT Claim Set"

### ISSUE THREAD

**Issue by TallTed** [w3c/vc-jose-cose#305]
_Originally posted by @TallTed in https://github.com/w3c/vc-jose-cose/pull/304#discussion_r1778819303_

> Is this accurate? We're restricting use of JWT Claim Names `vc` and `vp` in *any* JWT Claim Set, even a JWT Claim Set that does not encode a Verifiable Credential or Verifiable Presentation?

**Comment by decentralgabe** [comment]
line in question https://github.com/w3c/vc-jose-cose/blob/main/index.html#L607

**Comment by TallTed** [comment]
[The text that was problematic](https://github.com/w3c/vc-jose-cose/commit/41b73cca80ebfee7b221087414681504275e9b7c#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R317-R318):
```
                  The JWT Claim Names <code>vc</code> and <code>vp</code>
                  MUST NOT be present in any JWT Claim Set.
```
— has been changed to this —
```
                  The JWT Claim Names <code>vc</code> and <code>vp</code>
                  MUST NOT be present.
```

My immediate issue has been resolved, but I am VERY concerned that [there's no commit showing the change in the commit history](https://github.com/w3c/vc-jose-cose/commits/main/)!

**Comment by decentralgabe** [comment]
this is the commit https://github.com/w3c/vc-jose-cose/commit/41b73cca80ebfee7b221087414681504275e9b7c#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L287

**Comment by TallTed** [comment]
That commit changed —
```
            The JWT Claim Names <code>vc</code> and <code>vp</code>
            MUST NOT be present in any JWT Claims Set that comprises a
            Verifiable Credential or a Verifiable Presentation.
```
— to —
```
                  The JWT Claim Names <code>vc</code> and <code>vp</code>
                  MUST NOT be present in any JWT Claim Set.
```
The missing commit change `present in any JWT Claim Set.` to `present.` as is currently in the main branch.

Wormholes and alternate realities are bad.

**Comment by decentralgabe** [comment]
@TallTed I believe I found the commit here https://github.com/w3c/vc-jose-cose/commit/5e36a96337c9fd9e6af0d553ee0d79579d5008b2

I agree this was tough to find because of squash merging, which I've disabled.

**Comment by TallTed** [comment]
As noted on #307, that fixes line ~318.

There were two other similarly-phrased paragraphs, at line ~607 and ~1179, which I found by viewing this file on the main branch, and searching for MUST NOT be present. 

(Something else changed while I was doing the above, as ~1179 is no longer present, but ~607 still remains.)

I remain concerned about other changes that may have been made, and then un-made by other squash merges, without being noticed because they're not on spots that have been brought to light by specific review.
