### ISSUE TITLE
Address the `alg` language per the comment here

### ISSUE THREAD

**Issue by OR13** [w3c/vc-jose-cose#37]
> We may need to beef up the language about inclusion of alg as a required header parameter, but we could do that in a separate PR.

https://github.com/w3c/vc-jwt/pull/11#pullrequestreview-1165495004

**Comment by Sakurann** [comment]
+1

> If only the proof [property](https://www.w3.org/TR/vc-data-model/#dfn-property) is needed for the chosen signature method (that is, if there is no choice of algorithm within that method), the alg header MUST be set to none.

I think alg = none should not be allowed. what is the point of using **verifiable** credentials if there is no integrity protection..

**Comment by OR13** [comment]
> I think alg = none should not be allowed. what is the point of using verifiable credentials if there is no integrity protection...

I agree with you, but the VCWG decided to define VPs exactly this way.

If this document forbids `alg: none` in a VC-JWT, there are use cases that data integrity can handle that jwt cannot.

I think it's probably worth accepting the deviation there are explicitly forbid `alg: none` in the header of either a VC or a VP.

**Comment by Sakurann** [comment]
What are those use-cases? (Or where can I read them up?)

alg=none in VP-JWT does not make sense to me. What kind of information in a presentation is useful without a cryptographic holder binding that VP-JWT gives? Just send VC-JWT instead of an unsigned VP-JWT, no?

alg=none in VC-JWT also does not make much sense, but I am more willing to accept there might be issuers who want to reuse the syntax of VC-data-model (but than why not sign...)

**Comment by OR13** [comment]
> alg=none in VP-JWT does not make sense to me. 

https://www.w3.org/TR/vc-data-model/#presentations-0

^ basically how does vc-jwt support this use case... its ok if it doesn't... but better to be explicit about this.

> alg=none in VC-JWT also does not make much sense

Agreed, also, its probably illegal... depending on your definiton of "external proof".

https://www.w3.org/TR/vc-data-model/#proofs-signatures

**Comment by OR13** [comment]
@Sakurann recent PRs elaborated on this in great detail, based on conformance to the normative requirements of the core data model... please review.

cc @mprorock @selfissued 

Due to the core data model stating `proof` is optional, I will object to creating an incompatibility in functionality. 

But I am happy to discuss in depth.

**Comment by OR13** [comment]
I'm marking pending close, on the offhand chance, folks doing the review, feel the current text is sufficient.

**Comment by OR13** [comment]
Marked pending close over 1 week ago, closing.
