### ISSUE TITLE
clarify that `vc` `vp` claims do not include entire VC/VPs

### ISSUE THREAD

**Issue by Sakurann** [w3c/vc-jose-cose#4]
`vc` and `vp` claims in the JWT encoding include only the properties such as `@context`, `credentialSubject` that do not have equivalent IANA registered JWT claims such as `expirationDate`, `id`, etc. 

`vc` and `vp` claims do not include **entire** VC/VPs, which is not clear from the description below. 

> * vc: JSON object, which MUST be present in a JWT verifiable credential. The object contains the verifiable credential according to this specification.
> * vp: JSON object, which MUST be present in a JWT verifiable presentation. The object contains the verifiable presentation according to this specification.

Suggest to clarify the description to something like following (happy to do a PR):

> * vc: JSON object, which MUST be present in a JWT verifiable credential. The object contains the verifiable credential data model claims defined in this specification that do not have equivalent IANA registered JWT claims.
> * vp: JSON object, which MUST be present in a JWT verifiable presentation. The object contains the verifiable presentation data model claims defined in this specification that do not have equivalent IANA registered JWT claims.

**Comment by OR13** [comment]
short answer is that they do when you pick the `in addition to...` path.. which is what we recommend.

**Comment by TallTed** [comment]
> [@OR13] short answer is that they do when you pick the `in addition to...` path.. which is what we recommend.

I *think* you're saying that "[`vc` `vp` claims] do [include entire VC/VPs] when you pick the `in addition to...` path,_" in response to the title, but I'm not _sure_, because there's a lot more text in this issue that "they" might refer back to.

**Comment by OR13** [comment]
@TallTed thats correct, I am addressing the title of this issue.

In this implementation: https://github.com/transmute-industries/verifiable-credentials

I chose the `in addition to` path, because it's legal according to v1.1 and it has the added benefit of keeping the `vc` and `vp` claims spec compliant __without_ translation.

If you choose to implement the `instead of` path, you would need to transform these claims into "v1.1 compliant" data models after verification... and on the issuance side, from compliant data model into "intermediate non compliant" representations.

This is another reason why `in addition to` is simpler when compared to `instead of`.

**Comment by Sakurann** [comment]
since this is v2 and we are allowed to make breaking changes...

From the discussions, below seems to be an option that minimizes the need for mapping/transfrming between "vc-data-model" properties and existing registered JWT Claims while correctly uses existing registered JWT Claims enabling to reuse JWT libraries:

- `exp` JWT Claim is used for the expiration of a JWS signature, so not mapped to `ValidUntil` property in the "vc-data-model" (currently mapped to `expirationDate`)
- `iss` JWT Claim is used for the expiration of a JWS signature, so not mapped to `ValidFrom` property in the "vc-data-model" (currently not mapped to anything)
- `vc` JWT claim is an object that contains `
    - `ValidFrom` property of the "vc-data-model" (used to be mapped to `nbf` JWT Claim)
    - `id` property of the "vc-data-model" (used to be mapped to `jti` JWT Claim)
    - `credentialSubject.id` property of the "vc-data-model" (used to be mapped to `sub` JWT Claim)
    - the spec says that when `vc` JWT claim is present, `nbf`, `id`, `sub` JWT Claims MUST NOT be present
- `aud` JWT Claim definition is as in vc-data-model v1.1 not mapped to any property in the "vc-data-model"

(focusing on the JWT body claims since there are issues for each of the JOSE header claims (`alg` (#37), `kid` (#30) , `typ` (#5))

**Comment by OR13** [comment]
Under 1.1 rules, I think making the `vc` property a valid `application/credential+ld+json` is my preferred solution to this problem.

I am a strong -1 to "almost" `application/credential+ld+json` being legal in v2 for the `vc` property.

**Comment by Sakurann** [comment]
> Under 1.1 rules, I think making the vc property a valid application/credential+ld+json is my preferred solution to this problem.

Ah, that's interesting. In that case, would you define "vc" property similar to what I propose above or as something different? 

> I am a strong -1 to "almost" application/credential+ld+json being legal in v2 for the vc property.

Not sure I understand. what is "almost" application/credential+ld+json..

**Comment by David-Chadwick** [comment]
@Sakurann I think you have some typos in your message about the JWT claims. Specifically

`exp ` JWT Claim is used for the expiration of a JWS signature, so not mapped to ValidUntil property in the "vc-data-model" (currently mapped to expirationDate)
`iat` JWT Claim is used for the creation of a JWS signature, so not mapped to ValidFrom property in the "vc-data-model" (currently not mapped to anything)
`vc` is a JWT claim that contains a complete Credential (no modifications to it) - Note the JWT contains the proof to make it verifiable.
Similarly
`vp` is a JWT claim that contains a complete Presentation (no modifications to it).

**Comment by OR13** [comment]
> Not sure I understand. what is "almost" application/credential+ld+json..

An object that is conformant except without any properties that can map to a JWT.... aka the "instead of path".

I am ok giving that content type a unique `cty` though.

**Comment by OR13** [comment]
I'm going to mark this pending close, since AFAIK, its been overtaken in the latest draft, but I have filed https://github.com/w3c/vc-jwt/issues/119

Which I think is a better place to follow up on managing v1 vs v2 compatibility.

**Comment by TallTed** [comment]
> I have filed https://github.com/w3c/vc-jwt/issues/119 Which I think is a better place to follow up on managing v1 vs v2 compatibility.

It seems to me that a better place to follow up on managing v1 vs v2 compatibility would be an issue with exactly that focus and title, rather than one asking whether to deprecate `vc` and `vp`...

**Comment by OR13** [comment]
https://github.com/w3c/vc-jwt/pull/124

**Comment by OR13** [comment]
Marked pending close over 1 week ago, closing.
