### ISSUE TITLE
clearer wording for step 2

### ISSUE THREAD

**Issue by TallTed** [w3c/vc-jose-cose#43]
_Originally posted by @TallTed in https://github.com/w3c/vc-jwt/pull/41#discussion_r1083134664_

Step 2 reads —
```
Removing any properties from the <code>application/credential+ld+json</code> that were mapped.
```

I had suggested —
> Step 2 might be better reworded to the following, but I'm not certain this is the meaning that was intended.
> ```
> Remove any properties that were mapped from the <code>application/credential+ld+json</code>.
> ```

I think this should be changed to my suggested wording, if the intent is to remove the properties from the mapping.  As written, it could easily be understood to mean the properties should be removed from `the <code>application/credential+ld+json</code>`, which I'm sure was not intended.

**Comment by OR13** [comment]
This issue seems stale, we don't use these media types anymore.

Possibly this can be closed when #88 is merged?

**Comment by TallTed** [comment]
> we don't use these media types anymore

That's irrelevant.

However, the [changes that were inserted](https://github.com/w3c/vc-jwt/pull/41/files) in #41 appear to no longer be present in the master branch, and I am not able to quickly locate them anywhere else, so this issue does appear to be stale, and should be closed if no-one else knows of the existence of the troublesome steps.

**Comment by OR13** [comment]
Marked pending close over 1 week ago, closing.
