### ISSUE TITLE
Change spec name?

### ISSUE THREAD

**Issue by OR13** [w3c/vc-jose-cose#49]
How can we name this work item is such a way that it communicates our intention to support both JSON and CBOR and follow IETF conventions for JOSE / COSE?

`vc-jose-cose` ?

`vc-tokens` ?

**Comment by mprorock** [comment]
`Compact Verifiable Credentials expressed through Object Signing and Encryption`

**Comment by OR13** [comment]
This issue can be closed when https://github.com/w3c/vc-jwt/pull/115 is merged

**Comment by Sakurann** [comment]
PR merged
