### ISSUE TITLE
Support for multiple signatures

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-jose-cose#6]
This is a v2 issue. We should document how we can add multiple signatures to credentials and presentations using both external and internal proofs. (The v1.1 spec for JWT uses the compact serialisation, whereas multiple proofs *may* require the JSON serialisation)

**Comment by David-Chadwick** [comment]
Resolving this issue has now become something of a priority for members of the NGI Atlantic project, as we have said we will be "indicating to the community how multiply-signed VCs can be supported using JSON signatures and feeding this into VCDM v2.0."  We see two alternative methods for this:
- serial (or onion) signatures for VCs, where the output JWT of the first signer becomes the payload for the second signer, recursively. The RP would need to unwrap the JWTs one by one validating each signature in turn; or
- concurrent signatures which use the JWS JSON serialisation from RFC 7515 for creating a VC. Since VCs are not carried as tokens (unlike normal JWTs), then the compact serialisation is not essential for VCs.
No changes to the standard are needed for serial signatures (but implementation guidelines might be helpful). However changes are needed for concurrent signatures. In the coming weeks we will be documenting this and then implementing it in a month (or two max)

**Comment by theblockstalk** [comment]
We are currently leading a multi-signature implementation of VCs that uses the Verifiable Conditions Spec

See:
- https://github.com/w3c-ccg/verifiable-conditions
- https://github.com/Tonomy-Foundation/did-jwt-vc/pull/1 (work in progress)
- https://github.com/Tonomy-Foundation/did-jwt/pull/1 (work in progress)

**Comment by theblockstalk** [comment]
I'll be discussing this at the Tuesday W3C CCG weekly meeting. This is the content:
https://docs.google.com/presentation/d/1DsjJOfOCMhfXJgATbQAt6Ugk9Vmbq0zVrzL8thgsGVI

**Comment by David-Chadwick** [comment]
@theblockstalk Your proposed method is still at the experimental stage I believe, and relies on the variable-conditions CCG document. In the NGI Atlantic project we are looking for a method that can build on existing infrastructures and tools to aid user acceptance and quicker deployments. Most users wont be using DID documents I think, but rather will use did:key or the newer did:jwk. So our multi-signature method will take a more pragmatic approach and build on these.

**Comment by selfissued** [comment]
To be clear, JWTs don't support multiple signatures.  So I believe this request is out of scope for VC-JWTs.

I'm fine with there being other means of securing VCs that do support multiple signatures, possibly such as using the JWS JSON Serialization https://www.rfc-editor.org/rfc/rfc7515.html#section-7.2 .

But for the purposes of VC-JWT, I believe that this issue should be closed.

**Comment by David-Chadwick** [comment]
To be even clearer, there are two ways of doing multiple signatures: sequential and concurrent. We can use JWTs for sequential multiple signatures, since the JWT output from the first signature becomes the body of the second one. We could document this. But I agree that for concurrent signatures we cannot use a JWT but can use JSON Serialisation

**Comment by Sakurann** [comment]
> the JWT output from the first signature becomes the body of the second one. We could document this.
it will blow the size up but this sounds like the most realistic option.

> we cannot use a JWT but can use JSON Serialisation
since this is about signing using JWS, and the body does not have to JWT which only allows for compact serialization, defining JSON serializationis should be viable

**Comment by OR13** [comment]
This needs to be addressed at IETF, not here.

**Comment by OR13** [comment]
Marked pending close over 1 week ago, closing.
