### ISSUE TITLE
Add guidance on what to do id `proof` is present in VC-JWT

### ISSUE THREAD

**Issue by Sakurann** [w3c/vc-jose-cose#62]
A default behavior would be to ignore the `proof` claim in a VC-JWT that is not understood by VC-JWT implementation, so I am not sure this is actionable, but wanted to document based on the recent developments in vcdm spec.

i am still thinking what should be said, but I think some kind of guidance is needed what to do if there is a JWS signature and another signature in a proof property inside a payload. maybe provide guidance that implementers should have a policy what to do when that happens (ie reject the VP, make sure to process both signatures, etc.)

**Comment by OR13** [comment]
I think we have addressed this in recent PRs, @Sakurann can you confirm?
