### ISSUE TITLE
How to include credential metadata in vc + jwt encoding

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-jose-cose#64]
The VCDM contains a lot of credential metadata properties such as Terms of Use, Evidence, etc. that are not subject claims.
It is not clear how any of these properties can be transferred in a vc+jwt encoding since the mapping rules in section 3.4 state 

"Extract iss, sub, iat, nbf, exp, jti, and aud as registered claims.
Set aside all other claims as subject claims."

But ToU, Evidence etc are not subject claims. 

How do we address this issue?

**Comment by OR13** [comment]
@David-Chadwick IMO, this issue is answered by the current text, and especially the sections on processing registered claims.

Data could got in the header, or in the payload, and could be defined in the context or issuer dependent.

**Comment by David-Chadwick** [comment]
`Data could got in the header, or in the payload, and could be defined in the context or issuer dependent.`

This is hardly a standard. A standard should say exactly how something must be done so that everyone is singing from the same hymn sheet. "could be.." has no place in a standard.

**Comment by OR13** [comment]
@David-Chadwick I disagree, many standards are left intentionally flexible.

I don't understand how to address your issue here, I suggest you work in the core data model to provide clarity on this.

If you disagree, please simply reopen the issue.

**Comment by David-Chadwick** [comment]
please re-open as I disagree. Furthermore, the link to the latest version of the document (https://w3c.github.io/vc-jwt/) pointed to from the top page (https://github.com/w3c/vc-jose-cose) is broken, so it is not possible to easily find the latest draft.

**Comment by OR13** [comment]
@David-Chadwick I reopened the issue, but I don't know how to resolve it.

There seems to be confusion regarding how the core data model works.

The core data model says vc+ld+json is a JSON claimset... Which can include meta data about a credential, claims about a subject, and optionally embedded proofs.

JOSE has protected headers, which can contain JSON... Including JSON-LD or parts of the claimset.


The mapping rules you refer to apply only to v1.1

There are no mapping rules in version 2.

If you put claims in the payload, they are either defined in the V2 context or not.

If you put claims in the protected header, they are either in the IANA registry or not.

We removed the v1.1 mapping, and while there is still an experimental mapping for V2, we expect it to also be removed, and currently @selfissued is the only party requesting changes.

See #88.

**Comment by mprorock** [comment]
I think this issue no longer applies and we should close

**Comment by David-Chadwick** [comment]
Can you fix this broken link please (https://w3c.github.io/vc-jwt/) so that one can easily read the latest editors draft. Thanks

**Comment by OR13** [comment]
@David-Chadwick I can't its blocked by the short name change... we are waiting on confirmation from @iherman

**Comment by iherman** [comment]
> Can you fix this broken link please (https://w3c.github.io/vc-jwt/) so that one can easily read the latest editors draft. Thanks

@David-Chadwick that link is gone, because the WG decided to change the short name of the spec (and, to my surprise and a bit of disappointment, while GitHub is great to redirect URLs from old to new when they concern repository names, it does not for the GitHub "pages" feature). 

This is a long way of saying that you have to use https://w3c.github.io/vc-jose-cose/ from now on.

**Comment by David-Chadwick** [comment]
@iherman Thanks for the new pointer. This works fine now.

**Comment by David-Chadwick** [comment]
@OR13 "There are no mapping rules in version 2."
This is a problem to me. If I follow section 3 of the draft spec, then I am given no guidance of how to turn the claim set of section 3.2 into a VC that conforms to the VCDMv2. In my opinion these mapping rules must be part of the specification. otherwise implementors are likely to use different mapping rules and end up with different VCs.

**Comment by Sakurann** [comment]
I think the sentence that @David-Chadwick was originally referring to is gone, but I agree with a problem statement that is needs to be defined where to find which claims. 

"verification process" in vc-jose-cose points to a definition in vc-data-model, which I think is to avoid having to define where to find which claim, but "how to validate a signed VC" is a needed section - people do not validate even where there are clear validation rules. it is scary to think how much they will validate without clear validation rules..

**Comment by selfissued** [comment]
We have verification rules in the "Securing Verifiable Credentials" section at https://w3c.github.io/vc-jose-cose/#securing-verifiable-credentials .  @Sakurann and @David-Chadwick , what would you like to see added to that to satisfy this issue, or are we already there?

**Comment by David-Chadwick** [comment]
Let me check that this issue has now been adequately addressed. Please do not close until I confirm this

**Comment by David-Chadwick** [comment]
What will finally address this issue and make it crystal clear to everyone is to update example 1 by adding at least one metadata property to the VC, for example, credentialSchema e.g.
"credentialSchema": {
    "id": "https://example.org/examples/degree.json",
    "type": "JsonSchema"
  },
then implementors will easily be able to see how other extensions can be added

**Comment by David-Chadwick** [comment]
PR#159 resolves this

**Comment by selfissued** [comment]
Closing this, since addressed by the PR.
