### ISSUE TITLE
(English) references to the VCDM spec are wrong in the 1.1 section

### ISSUE THREAD

**Issue by iherman** [w3c/vc-jose-cose#66]
Provided that the answer to the question in #65 is that the 1.1 section should be left in the spec (albeit updated), there are a number of references to the VCDM which are wrong. For example, §2.2.1 starts with

> To encode a [verifiable credential](https://www.w3.org/TR/vc-data-model/#dfn-credential) as a JWT, specific [properties](https://www.w3.org/TR/vc-data-model/#dfn-property) introduced by this specification MUST be either:

but the English references "by this specification" is wrong: it should be replaced by a reference to the VCDM spec. This is an obvious leftover of the fact that this part of the spec was copy pasted from the VCDM 1.1 document. The whole §2.2 section should be revised in this respect. This must be done, in my view, **_before_** this document is published as a FPWD.

**Comment by TallTed** [comment]
> This must be done, in my view, before this document is published as a FPWD.

It will cause no harm to publish FPWD before this (known issue, tracked here) is fixed.

**Comment by OR13** [comment]
I have started to address this in https://github.com/w3c/vc-jwt/pull/68

It will probably take a few passes to make these sections read smoother.

**Comment by OR13** [comment]
This issue is stale and should be closed.
