### ISSUE TITLE
typ for COSE

### ISSUE THREAD

**Issue by OR13** [w3c/vc-jose-cose#67]
There is no registered tag for `typ` in COSE. 

This prevents following the guidance from the JWT BCP

**Comment by cghost420** [comment]
I don't know how to use github so I'm trying to figure out how to fix this. Lots of reading so bear with me. Can i do a pull request then merge?

**Comment by Sakurann** [comment]
should point to an ietf draft here now https://www.ietf.org/archive/id/draft-ietf-cose-typ-header-parameter-00.html

**Comment by Sakurann** [comment]
PR merged

**Comment by cghost420** [comment]
OK, I looked into it. It can be referenced to an rfc but I have to give
them credit for the reference. That's one way or I could manually change
it. Any thoughts on this?
