### ISSUE TITLE
Add guidance on mapping to the core data model

### ISSUE THREAD

**Issue by OR13** [w3c/vc-jose-cose#69]
Beyond proving that a mapping is possible.

Should using the mapping be encouraged?

Should we attempt to make the mapping bi directional?

For example:

`vc+jwt` -> `vc+ld+json` vs `vc+jwt` <-> `vc+ld+json`

**Comment by OR13** [comment]
See the original comment on:

- https://github.com/w3c/vc-jwt/pull/68/files#r1154484933

**Comment by OR13** [comment]
Here is some straw man guidance text to trigger discussion:

Implementers that require RDF processing of Verifiable Credentials in JSON-LD format are advised to perform a one way mapping prior to RDF / JSON-LD processing. This could be part of a data import process pipeline or to support data visualization.

It is not recommended to map from `vc+ld+json` to JWT because the integrity of the claims could have been compromised due to JSON reordering, and because there is no way to ensure that the correct header or signature values have been preserved.

**Comment by iherman** [comment]
> 
> It is not recommended to map from `vc+ld+json` to `vc+jwt` because the integrity of the claims could have been compromised due to JSON reordering, 

I am not sure I understand this argument. The order of the statements in JSON-LD are not significant, they map to the same graph anyway. Can you explain what you mean?

**Comment by OR13** [comment]
@iherman the order to JSON members matters when verifying a json web signature and the full quote includes:

> and because there is no way to ensure that the correct header or signature values have been preserved.

**Comment by OR13** [comment]
This will be closed when #88 is merged

**Comment by OR13** [comment]
Marked pending close over 1 week ago, closing.

Also core data model PR has the action now: https://github.com/w3c/vc-data-model/pull/1203
