### ISSUE TITLE
Update guidance for `application/vc+jwt`

### ISSUE THREAD

**Issue by OR13** [w3c/vc-jose-cose#72]
See https://github.com/w3c/vc-jwt/pull/68#discussion_r1160065101

We probably want to make the "note" a normal paragraph or advisement.

The class is just a styling for readability.

**Comment by OR13** [comment]
This will be closed when https://github.com/w3c/vc-jwt/pull/88 is merged

**Comment by Sakurann** [comment]
PR #88 was merged
