### ISSUE TITLE
Handling of "type" not clear in v2

### ISSUE THREAD

**Issue by astanciu** [w3c/vc-jose-cose#76]
When converting from `vc+ld+jwt` to `vc+jwt`, it's not clear how to handle the `type` property of the VCDM. 

For ex, in the examples folder of this repo, the [examples/vc-2.0/vc-ld-jwt.jose](https://github.com/w3c/vc-jwt/blob/main/examples/vc-2.0/vc%2Bld%2Bjwt.jose) decodes to a VC that contains:
```

  "type": [
    "VerifiableCredential",
    "UniversityDegreeCredential"
  ],

```

The 2.0 version, [examples/vc-2.0/vc-jwt.jose](https://github.com/w3c/vc-jwt/blob/main/examples/vc-2.0/vc%2Bjwt.jose), (which presumably is the same VC converted to `vc-jwt`) does not contain any notion of the `UniversityDegreeCredential` type.

What is the guidance here? When converting to, or constructing, a `vc-jwt` using the new 2.0 spec, should the additional types (beyond the default `VerifiableCredential`) be included in the jwt as custom claims or something else?

**Comment by OR13** [comment]
<img width="912" alt="Screen Shot 2023-05-01 at 3 34 36 PM" src="https://user-images.githubusercontent.com/8295856/235526326-1c9914a1-30c7-4afa-a623-21d1e71e87e0.png">

The spec could be much, much clearer on this, but essentially... 

The point of `vc+jwt` is that you don't need to convert from JSON-LD to JSON claimset.

Here is a demo https://jwt.vc

Here is the transforming code, that goes from `vc+jwt` or `vc+ld+jwt` to `vc+ld+json` (unidirectional mapping).

https://github.com/transmute-industries/jwt.vc/blob/main/services/token.ts

The group is still discussing many issues related to this, but hopefully we will agree to better text in these sections soon.

**Comment by OR13** [comment]
`type` is RDF Class, this question seems more about the core data model.

**Comment by OR13** [comment]
Marked pending close over 1 week ago, closing.
