### ISSUE TITLE
Add external references to Privacy and Security sections

### ISSUE THREAD

**Issue by mprorock** [w3c/vc-jose-cose#81]
We should extend out with multiple references to NIST and similar in relevant sections

**Comment by mprorock** [comment]
e.g. maybe https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-122.pdf

**Comment by selfissued** [comment]
I've labeled this as post-CR because it wouldn't change normative requirements in the specification.  This is a nice-to-have.  If someone creates a PR adding additional references, great.
