### ISSUE TITLE
Accessibility Self-Review for VC-JWT

### ISSUE THREAD

**Issue by OR13** [w3c/vc-jose-cose#94]
The following is an Accessibility Self-Review for VC JWT, namely the following specifications:

  * [Securing Verifiable Credentials using JSON Web Tokens](https://www.w3.org/TR/vc-jwt/)

The specification listed above is a cryptographic message securing mechanisms and thus do not contain text, visuals, audio, or haptic data that will be experienced directly by a human being.

The one exception for this is possibly software developers, who might encounter error messages when using software libraries that implement the specification above. 

The errors have specific codes, which are internationalizable, but whose internationalization characteristics are up to each implementer. 

We believe that this specification, in general, does not create accessibility concerns, but are curious to know if we have overlooked some aspect of how these technologies will be used that will create accessibility issues.

The following self-review question categories were analyzed and resulted in the following answers:

* The technology DO NOT allow for visual rendering of content
* The technology DO NOT provide author control over color
* The technologies DO NOT provide features to accept user input
* The technologies DO NOT provide user interaction features
* The technologies DO NOT define document semantics
* The technologies DO NOT provide time-based visual media
* The technologies DO NOT provide audio
* The technologies DO NOT allow time limits
* The technologies DO NOT allow text content
* The technologies DO NOT create objects that don't have an inherent text representation
* The technologies DO NOT provide content fallback mechanisms, whether text or other formats
* The technologies DO NOT provide visual graphics
* The technologies DO provide internationalization support
  * Accessibility features can be internationalized to the same degree as other features
* The technologies DO NOT define accessible alternative features
* The technologies DO NOT provide content directly for end-users
* The technologies DO NOT define an API
* The technologies DO NOT define a transmission protocol

**Comment by OR13** [comment]
This seems ready, I removed the WIP tag

**Comment by Sakurann** [comment]
the specification name and short has changed:
- name: from "Securing Verifiable Credentials using JSON Web Tokens" to "Securing Verifiable Credentials using JOSE and COSE"
- shortname: from vc-jwt to vc-jose-cose

**Comment by awoie** [comment]
@OR13 Requested horizontal review from APA here https://github.com/w3c/a11y-request/issues/68

**Comment by OR13** [comment]
closing, we'll address follow ups as they come
