### ISSUE TITLE
Guidance on collisions between VC property names and registered JWT claims

### ISSUE THREAD

**Issue by andresuribe87** [w3c/vc-jose-cose#98]
Imagine that we start with the core VCDM (i.e. `application/vc+ld+json`) and want to secure it according to Section 3 (Securing the Core VC Data Model). The VCDM may have additional property fields defined by the issuer (for the sake of this example, let's say the issuer populated a `verified_claims` property). If interpreted as a JWT, the claim who's name is `verified_claims` was registered in [this spec](https://openid.net/specs/openid-connect-4-identity-assurance-1_0-13.html#name-registry-contents).

What's the guidance on conflicting JWT Claim names and VC property names when securing the core VCDM? 

Personally, I think we should be wrapping the VCDM inside the `vc` registered claim; but it seems like we've moved in a different direction.

**Comment by OR13** [comment]
I think this has been addressed in recent PRs.

**Comment by Sakurann** [comment]
1149 in vcdm was merged and afaik there are no collision in vc property names and registered jwt claims anymore :)

**Comment by Sakurann** [comment]
1149 in vcdm was merged and afaik there are no collision in vc property names and registered jwt claims anymore :)

**Comment by Sakurann** [comment]
1149 in vcdm was merged and afaik there are no collision in vc property names and registered jwt claims anymore :)
